# Generated by Django 4.2.16 on 2024-10-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaexamen',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Categoría'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción del Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='tipocategoria',
            name='valor_maximo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Máximo'),
        ),
        migrations.AlterField(
            model_name='tipocategoria',
            name='valor_minimo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor Mínimo'),
        ),
    ]
