# Generated by Django 4.2.16 on 2024-10-16 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoriaexamen_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Marca de Medicamento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Medicamento',
                'verbose_name_plural': 'Tipos de Medicamentos',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='duracion_cita',
            field=models.IntegerField(default=30, verbose_name='Tiempo de Atencion(minutos)'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='marca_medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marca_medicamentos', to='core.marcamedicamento', verbose_name='Marca'),
        ),
    ]
